#ifndef GENERIC
#define GENERIC

#define UPPERCASE_CHAR_MAX 90
#define UPPERCASE_CHAR_MIN 65
#define LOWERCASE_CHAR_MAX 122
#define LOWERCASE_CHAR_MIN 97

#define DISTANCE_FROM_UPPER_TO_LOWER_CHAR (LOWERCASE_CHAR_MAX - UPPERCASE_CHAR_MAX)
#define UPPERCASE_CHAR_CHECK(c) ((c) >= UPPERCASE_CHAR_MIN && (c) <= UPPERCASE_CHAR_MAX)
#define LOWERCASE_CHAR_CHECK(c) ((c) >= LOWERCASE_CHAR_MIN && (c) <= LOWERCASE_CHAR_MAX)


#endif
